[phases.setup]
nixPkgs = ["python311", "postgresql", "redis"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["alembic upgrade head"]

[start]
cmd = "python start.py"
